# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99006304183e65b4da5f6cb69c4c61ceb2677ce85968408e0f1fba02c559e0caf340c5a5278fbc4d37a501a10981ca1c3ce93ad806b8504a9108c773d4b92908

test:
  secret_key_base: 2b2c543df5ab00c3665cb233ecc52027538449394afbf0d2170941b2d8e057e97174b0134f1bbd7838ba9af0457b4fa5886b7225abeb485e99f75e2a2aecd7a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
